// Message union: every state change begins here as a fact about
// something that happened. Verb-first past-tense names, no NoOp.

import { Schema } from 'effect'
import { defineMessageUnion } from 'foldkit/message'

export const Message = defineMessageUnion({
  RequestedAddNode: { x: Schema.Number, y: Schema.Number },
  ChangedNewNodeType: { nodeType: Schema.String },
  ChangedSearch: { text: Schema.String },
  SelectedSearchResult: { nodeId: Schema.String },
  ClearedSearch: {},
  ChangedZoom: { valueText: Schema.String },
  StartedNodeDrag: {
    nodeId: Schema.String,
    x: Schema.Number,
    y: Schema.Number,
  },
  StartedPan: { x: Schema.Number, y: Schema.Number },
  StartedMarquee: {
    worldX: Schema.Number,
    worldY: Schema.Number,
    worldPerPixel: Schema.Number,
    screenX: Schema.Number,
    screenY: Schema.Number,
  },
  MovedPointer: { x: Schema.Number, y: Schema.Number },
  EndedDrag: {},
  ClickedCanvas: {},
  SelectedNode: { nodeId: Schema.String },
  HoveredEdge: { edgeId: Schema.String },
  UnhoveredEdge: { edgeId: Schema.String },
  SelectedEdge: { edgeId: Schema.String },
  ClickedPort: { nodeId: Schema.String, port: Schema.String },
  CancelledPending: {},
  OpenedContextMenu: {
    worldX: Schema.Number,
    worldY: Schema.Number,
    clientX: Schema.Number,
    clientY: Schema.Number,
  },
  ChangedContextMenuSearch: { text: Schema.String },
  SelectedContextMenuNode: { nodeType: Schema.String },
  DismissedContextMenu: {},
  PreventedNativeContextMenu: {},
  ToggledMinimap: {},
  UpdatedParam: {
    nodeId: Schema.String,
    key: Schema.String,
    valueText: Schema.String,
  },
  RequestedDeleteSelection: {},
  PressedDelete: {},
  PressedCopy: {},
  PressedPaste: {},
  PressedUndo: {},
  PressedRedo: {},
  ZoomedIn: {},
  ZoomedOut: {},
  ResetView: {},
  ToggledSimulateLoading: {},
  ChangedLoadingVariant: { variant: Schema.String },
  RequestedSave: {},
  CompletedPersistGraph: {},
  FailedPersistGraph: { reason: Schema.String },
  CompletedLoadGraph: { json: Schema.String },
  CompletedLoadEmpty: {},
  FailedLoadGraph: { reason: Schema.String },
  RequestedNew: {},
  RequestedExport: {},
  CompletedExport: {},
  RequestedImport: {},
  CompletedImportFile: { text: Schema.String },
  CancelledImportFile: {},
  FailedImportFile: { reason: Schema.String },
  RequestedCopyHlsl: {},
  CompletedCopyHlsl: {},
  FailedCopyHlsl: { reason: Schema.String },
  DismissedStatus: {},
})
export type Message = typeof Message.Type
