// Message union: every state change begins here as a fact about
// something that happened. Verb-first past-tense names, no NoOp.

import { Schema } from 'effect'
import { defineMessageUnion } from 'foldkit/message'

export const Message = defineMessageUnion({
  RequestedAddNode: { x: Schema.Number, y: Schema.Number },
  ChangedNewNodeType: { nodeType: Schema.String },
  ChangedSearch: { text: Schema.String },
  SelectedSearchResult: { nodeId: Schema.String },
  ClearedSearch: {},
  ChangedZoom: { valueText: Schema.String },
  StartedNodeDrag: {
    nodeId: Schema.String,
    x: Schema.Number,
    y: Schema.Number,
  },
  StartedPan: { x: Schema.Number, y: Schema.Number },
  StartedGroupDrag: {
    groupId: Schema.String,
    x: Schema.Number,
    y: Schema.Number,
  },
  StartedMarquee: {
    worldX: Schema.Number,
    worldY: Schema.Number,
    worldPerPixel: Schema.Number,
    screenX: Schema.Number,
    screenY: Schema.Number,
  },
  MovedPointer: { x: Schema.Number, y: Schema.Number },
  EndedDrag: {},
  ClickedCanvas: {},
  SelectedNode: { nodeId: Schema.String },
  HoveredEdge: { edgeId: Schema.String },
  UnhoveredEdge: { edgeId: Schema.String },
  SelectedEdge: { edgeId: Schema.String },
  ClickedPort: { nodeId: Schema.String, port: Schema.String },
  CancelledPending: {},
  OpenedContextMenu: {
    worldX: Schema.Number,
    worldY: Schema.Number,
    clientX: Schema.Number,
    clientY: Schema.Number,
  },
  ChangedContextMenuSearch: { text: Schema.String },
  SelectedContextMenuNode: { nodeType: Schema.String },
  DismissedContextMenu: {},
  PreventedNativeContextMenu: {},
  SelectedGroup: { groupId: Schema.String },
  PressedGroupSelection: {},
  PressedUngroupSelection: {},
  RenamedGroup: { groupId: Schema.String, name: Schema.String },
  ChangedGroupColor: { groupId: Schema.String, color: Schema.String },
  InsertedRerouteOnEdge: {
    edgeId: Schema.String,
    worldX: Schema.Number,
    worldY: Schema.Number,
  },
  ConvertedRerouteToNamed: { nodeId: Schema.String },
  ConvertedNamedRerouteToReroute: { nodeId: Schema.String },
  AddedNamedRerouteUsage: { declarationId: Schema.String },
  RenamedReroute: { declarationId: Schema.String, name: Schema.String },
  SelectedRerouteUsages: { declarationId: Schema.String },
  SelectedRerouteDeclaration: { usageId: Schema.String },
  AlignedNodes: { mode: Schema.String },
  DistributedNodes: { axis: Schema.String },
  CollapsedSelection: {},
  ExpandedCollapsed: { collapsedId: Schema.String },
  RenamedCollapsed: { collapsedId: Schema.String, name: Schema.String },
  SelectedCollapsed: { collapsedId: Schema.String },
  OpenedNodeMenu: {
    nodeId: Schema.String,
    clientX: Schema.Number,
    clientY: Schema.Number,
  },
  DismissedNodeMenu: {},
  ToggledMinimap: {},
  UpdatedParam: {
    nodeId: Schema.String,
    key: Schema.String,
    valueText: Schema.String,
  },
  RequestedDeleteSelection: {},
  PressedDelete: {},
  PressedCopy: {},
  PressedPaste: {},
  PressedUndo: {},
  PressedRedo: {},
  ZoomedIn: {},
  ZoomedOut: {},
  ResetView: {},
  ToggledSimulateLoading: {},
  ChangedLoadingVariant: { variant: Schema.String },
  PressedEscape: {},
  PressedSettings: {},
  OpenedSettings: {},
  ClosedSettings: {},
  StartedShortcutRecording: { actionId: Schema.String },
  CancelledShortcutRecording: {},
  CapturedShortcut: {
    key: Schema.String,
    ctrlKey: Schema.Boolean,
    metaKey: Schema.Boolean,
    altKey: Schema.Boolean,
    shiftKey: Schema.Boolean,
    isApple: Schema.Boolean,
  },
  ResetShortcut: { actionId: Schema.String },
  ResetAllShortcuts: {},
  ChangedShortcutPlatform: { platform: Schema.String },
  CompletedLoadSettings: { json: Schema.String },
  CompletedLoadSettingsEmpty: {},
  FailedLoadSettings: { reason: Schema.String },
  CompletedPersistSettings: {},
  FailedPersistSettings: { reason: Schema.String },
  RequestedSave: {},
  CompletedPersistGraph: {},
  FailedPersistGraph: { reason: Schema.String },
  CompletedLoadGraph: { json: Schema.String },
  CompletedLoadEmpty: {},
  FailedLoadGraph: { reason: Schema.String },
  RequestedNew: {},
  RequestedExport: {},
  CompletedExport: {},
  RequestedImport: {},
  CompletedImportFile: { text: Schema.String },
  CancelledImportFile: {},
  FailedImportFile: { reason: Schema.String },
  RequestedCopyHlsl: {},
  CompletedCopyHlsl: {},
  FailedCopyHlsl: { reason: Schema.String },
  DismissedStatus: {},
})
export type Message = typeof Message.Type
